name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  firebase_messaging: ^14.7.4
  path_provider: ^2.1.1
  firebase_analytics: ^10.7.0
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
