// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5T29dTM9_dvZBWB2hkc94jl1knM7WIA',
    appId: '1:883544385929:web:def8fbf54aa22a8c25d958',
    messagingSenderId: '883544385929',
    projectId: 'project-inda',
    authDomain: 'project-inda.firebaseapp.com',
    storageBucket: 'project-inda.appspot.com',
    measurementId: 'G-CVGF3ZZRNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqqq9lXN3HIweDgqg9PBabbrt5MQ_Qr18',
    appId: '1:883544385929:android:07b57bb986f1f0fb25d958',
    messagingSenderId: '883544385929',
    projectId: 'project-inda',
    storageBucket: 'project-inda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUc-WjByVoUBPOEcyHGCa8KgUlvQ7ksc',
    appId: '1:883544385929:ios:801bac653a0f19fe25d958',
    messagingSenderId: '883544385929',
    projectId: 'project-inda',
    storageBucket: 'project-inda.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOUc-WjByVoUBPOEcyHGCa8KgUlvQ7ksc',
    appId: '1:883544385929:ios:81974ae456c9af0a25d958',
    messagingSenderId: '883544385929',
    projectId: 'project-inda',
    storageBucket: 'project-inda.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
